name: 'surfside-test'


services:
  valkey:
    volumes: []

  kafka:
    volumes: []
    environment:
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on: []

  clickhouse:
    volumes: ["./init/clickhouse-schema.sql:/docker-entrypoint-initdb.d/init.sql:ro"]
    depends_on: []

volumes: {}